name: dev-env

services:
  dev-env:
    build:
      context: .
      dockerfile: Dockerfile
    image: dev-environment:latest
    container_name: dev-env
    tty: true
    volumes:
      - .:/home:rw
